USE [master]
GO
/****** Object:  Database [catalog]    Script Date: 19/9/2024 14:03:22 ******/
CREATE DATABASE [catalog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'catalog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\catalog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'catalog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\catalog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [catalog] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [catalog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [catalog] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [catalog] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [catalog] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [catalog] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [catalog] SET ARITHABORT OFF 
GO
ALTER DATABASE [catalog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [catalog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [catalog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [catalog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [catalog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [catalog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [catalog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [catalog] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [catalog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [catalog] SET  DISABLE_BROKER 
GO
ALTER DATABASE [catalog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [catalog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [catalog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [catalog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [catalog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [catalog] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [catalog] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [catalog] SET RECOVERY FULL 
GO
ALTER DATABASE [catalog] SET  MULTI_USER 
GO
ALTER DATABASE [catalog] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [catalog] SET DB_CHAINING OFF 
GO
ALTER DATABASE [catalog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [catalog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [catalog] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [catalog] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'catalog', N'ON'
GO
ALTER DATABASE [catalog] SET QUERY_STORE = OFF
GO
USE [catalog]
GO
/****** Object:  Table [dbo].[TbProduct]    Script Date: 19/9/2024 14:03:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TbProduct](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[productName] [nvarchar](150) NOT NULL,
	[isDelete] [bit] NOT NULL,
	[createDate] [datetime] NOT NULL,
	[createBy] [int] NOT NULL,
	[updateDate] [datetime] NULL,
	[updateBy] [int] NULL,
 CONSTRAINT [PK_TbProduct] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [catalog] SET  READ_WRITE 
GO
